package sbpf

import (
	"encoding/binary"
	"testing"
)

func TestSolanaStaticSyscallHashGoldens(t *testing.T) {
	t.Parallel()
	// Cross-language values generated by the pinned Solana SDK's const
	// Murmur3-x86-32 implementation with seed zero.
	want := map[string]uint32{
		"sol_invoke_signed_c":          2720767109,
		"sol_log_":                     544561597,
		"sol_memcpy_":                  1904002211,
		"sol_memmove_":                 1128493560,
		"sol_memset_":                  930151202,
		"sol_memcmp_":                  1608310321,
		"sol_create_program_address":   2474062396,
		"sol_try_find_program_address": 1213221432,
	}
	for symbol, id := range want {
		if got := HashSymbolName(symbol); got != id {
			t.Errorf("HashSymbolName(%q) = %d (0x%08x), want %d (0x%08x)", symbol, got, got, id, id)
		}
	}
}

func TestStaticSyscallUsesV3ExternalCallEncoding(t *testing.T) {
	t.Parallel()
	const id uint32 = 2720767109 // sol_invoke_signed_c; bit 31 is set.
	call := StaticSyscall(id)
	if call.Op != CALL_IMM || call.Dst != 0 || call.Src != 0 || call.Offset != 0 || uint32(call.Immediate) != id {
		t.Fatalf("static syscall = %+v", call)
	}
	program := []Instruction{call, Return()}
	if err := ValidateProgram(program); err != nil {
		t.Fatalf("ValidateProgram: %v", err)
	}
	encoded, err := Encode(program)
	if err != nil {
		t.Fatal(err)
	}
	if len(encoded) != 2*InstructionSize || encoded[0] != byte(CALL_IMM) || encoded[1] != 0 || binary.LittleEndian.Uint32(encoded[4:8]) != id {
		t.Fatalf("encoded static call = %x", encoded)
	}
	decoded, err := Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if len(decoded) != 2 || uint32(decoded[0].Immediate) != id || decoded[0].Src != 0 {
		t.Fatalf("decoded static call = %+v", decoded)
	}
}
